### ISSUE TITLE
Really dirty rendering after relaunch

### ISSUE THREAD

**Issue by stefanhoth** [OpenTechSchool/www.opentechschool.org#161]
I may be late to the party but the relaunched site has a really bad rendering on Chrome 35 ( **Windows** ).

![dirty_ots](https://cloud.githubusercontent.com/assets/45467/3333705/66f04800-f7f6-11e3-8a9b-5159e6d596e6.jpg)

**Comment by Ivoz** [comment]
@stefanhoth to note, please remember in all issues you make online to use clear language. What isn't clear to me is what exactly you mean by "dirty rendering" and "really bad rendering". Giving clear descriptions of exactly what's broken makes things unambiguous for everybody and ensures everyone is talking about the same thing.

Anyway, I'm guessing by this you might mean the unaliased rendering of fonts, but this issue is not infact new, it has been present for a great while, probably over a year. So maybe you mean something else?

If you do mean that, then it is unfortunately a bug specific to Chrome on Windows; it uses an old text rendering API (GDI) which isn't up the task of nicely anti-aliasing custom web fonts. It's hard to find a satisfactory workaround that applies CSS to only Chrome on Windows (unfortunately, as opposed to IE!). This would also then be a duplicate of #96

**Comment by stefanhoth** [comment]
@Ivoz yes, I meant this issue and sorry for not making myself clear enough. 

Closed as a duplicate of #96. (But it's more apparent with the new design)
