### ISSUE TITLE
french translation for the about-section of the press page

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#71]
Putting you in charge of it, as I (for some reason can't assign it to @benoitbleuze). Would be awesome if you could provide a translation by tonight so we can add it before the launch tomorrow.

This is the original english version:

OpenTechSchool is a community initiative offering free programming workshops and meetups to technology enthusiasts of all genders, backgrounds and experience levels. It supports volunteer coaches in setting up the events taking care of the organizational details and encouraging them to create original teaching material, to be then openly shared online and further developed with contributions from the global OTS community. OTS' main goal is to crate a friendly learning environment where no one feels shy about asking any question. Everyone is invited to participate, whether as a coach or a learner, and get in contact to organize OTS events anywhere in the world.

**Comment by benoitbleuze** [comment]
Hej hej,
The reason is, I guess, easy enough: I am not part of
team-whatever-team-team, and I don't want to spend my life reading e-mail
on OTS management. I will create I pull request or something else if I
don't get access to the repo.

Amelie sent me the text already this morning., however I won't have time to
translate any of it before I come back home tonight. The text is short
enough I should have it by midnight at the latest.

Ben.

**Comment by benoitbleuze** [comment]
Hum didn want to create a new issue with my merge request, commit ab1e8b0 in issue #86
